### ISSUE TITLE
Server : Listy : Operacje na listach

### ISSUE THREAD

**Issue by kleo0** [kleo0/ShoppingList#3]
Obsługa zapytań

1. tworzenie / usuwanie
2. update: dodawanie / usuwanie elementów
3. zbieranie statystyk (ceny)

**Comment by sheadovas** [comment]
- d2c23aef25c3af81a6a12707f4b70e82f3f10ebf dodanie tworzenie listy
- e66e7abc0a225ffcab0f4e08dda8c4698063f814 dodanie pobierania aktualnej listy oraz usuwania

**TODO**

- przetestowanie zaimplemetnowanych featerów
- wrzucenie na server
- dodanie triggera usuwającego listę w przypadku gdy nikt już jej nie posiada

**Comment by sheadovas** [comment]
[Wiki: Operacje na listach](https://github.com/kleo0/ShoppingList/wiki/Zapytania-do-serwera#operacja-na-listach)

Oraz patch poprawiający działanie aktualnie zaimplementowanych akcji (bugfixy, przepisanie częściowo implementacji, więcej na wiki): 9bab49510360ab2c7c844ffcb7607b7dad82b596

**Comment by sheadovas** [comment]
3092ff5 Dodanie pobierania list, jednakże z jakiegoś powodu nie chce działać z PHP o_O. Query z poziomy mysql działa bez zarzutu

**Comment by sheadovas** [comment]
60985fccb0c4a2bb4e2f92c4cd7797608a7a1a4c Dodanie możliwości współdzielenia (o ile jesteśmy jej współwłaścicielem)

**Comment by sheadovas** [comment]
b7ed49a Dokończenie tworzenia list

**Comment by sheadovas** [comment]
3a8766e Dodanie modyfikowania list

**Comment by sheadovas** [comment]
be812db Naprawa niedziałającego usuwania elementów z list

**Comment by sheadovas** [comment]
c1d43d1 (force) Naprawa niedziałającego usuwania elementów z listy i czyszczenie bazy z pustych elementów
