### ISSUE TITLE
Server : Synchronizowanie list

### ISSUE THREAD

**Issue by kleo0** [kleo0/ShoppingList#4]
Obsługa zapytania do synchronizowania list

**Comment by sheadovas** [comment]
Do synchronizowania list mogą służyć akcje [GET](https://github.com/kleo0/ShoppingList/wiki/Zapytania-do-serwera#get) (pobieranie aktualnej listy) oraz [MOD](https://github.com/kleo0/ShoppingList/wiki/Zapytania-do-serwera#mod) (modyfikowanie listy w bazie)
