### ISSUE TITLE
App : Logika : Obsługa kamery

### ISSUE THREAD

**Issue by kleo0** [kleo0/ShoppingList#7]
Obsługa:

1.  robienie zdjęcia
2. przetworzenie go (w wersji alfa: nic, beta: zmniejszenie rozmiaru, rotacja, gamma: inne)
3. przekazanie go do warstwy OCR (analiza, bądź wysłanie do serwera)

**Comment by kleo0** [comment]
Zrobienie robienie zdjęcia w commicie: 483bb2e.

**Comment by sheadovas** [comment]
Wysyłanie obrazka do serwera, odbiór rozpoznanych danych oraz oznaczenie ich w liście zakupów znajduje się w commitach:

- eb89bd8aa0f747fe66865f0b4dfaf2cdc7db0c81
- ebba0cb1efbcb072332ff5382f5413377f3a4014
- ff401bdcf8c00609ff329ca440668e25c7975a23
