### ISSUE TITLE
App : Server : OCR

### ISSUE THREAD

**Issue by kleo0** [kleo0/ShoppingList#8]
1. Trening pod paragony
2. Raczej bez słownika
3. Parsowanie danych i przekazanie listy zakupionych przedmiotów do warstwy modyfuikującej listę zakupów

**Comment by sheadovas** [comment]
Przesuwamy pod drugą iterację, ponieważ jest to dość ciężki i długi temat do zrealizowania

**Comment by sheadovas** [comment]
Wystawienie odpowiedniego formularza obsługującego OCR

**Comment by sheadovas** [comment]
Formularz znajduje się wewnątrz: ebba0cb1efbcb072332ff5382f5413377f3a4014 (nowa akcja)
